### ISSUE TITLE
EPUB support?

### ISSUE THREAD

**Issue by marttt** [naihe2010/apvlv#15]
Hi,
Have you considered adding EPUB support to apvlv?

Sumatra PDF for Windows has it; Zathura for Linux also has a plugin (which I didn't get to work, though). But there seems to be no cross-platform tool that supports all three -- EPUB, PDF and DJVU. So add this, and you'll have a kind of perfect document reader with vi keybindings.

Thanks anyway for the great work!

**Comment by naihe2010** [comment]
apvlv supports EPUB now.
