### ISSUE TITLE
Feature request: follow internal links in pdf

### ISSUE THREAD

**Issue by simongkjn** [naihe2010/apvlv#26]
I've just switched to Apvlv as my main pdf viewer and have found it awesome so far! I was wondering if it would be possible to follow links included in a pdf (e.g.  links to section in the table of contents, or links to bibliography in the main text ...).

**Comment by naihe2010** [comment]
apvlv can jump internal link by pressing ']' and return the original page by pressing 't' like vim tags.
And, these key presses support pre number as command arguments.

**Comment by simongkjn** [comment]
Yes that works perfectly awesome! Somehow I couldn't find that in the docs. Also I had missed that apvlv supported visual mode, which is really great!

**Comment by aleprovencio** [comment]
not working here...
→ apvlv --version
apvlv 0.1.5-rel
