### ISSUE TITLE
mac osx installation

### ISSUE THREAD

**Issue by drselump14** [naihe2010/apvlv#29]
Does it work on mac os x?

**Comment by baotiao** [comment]
Yes I also waiting for the mac version.

**Comment by claudiocabral** [comment]
I got it to compile on os x and I'm currently running it after manually copying  Startup.pdf and main_menubar.glade to /usr/local/share/apvlv/doc/ (had to create both apvlv and doc folders)
If I get cmake to do that automaticaly I think we got ourselves a working version...

**Comment by drselump14** [comment]
@claudiocabral thank you for the effort ... I tried to do `make` from your code, but it says that gdk/dgkx.h not found ...

**Comment by claudiocabral** [comment]
hm, weird, I did a make before commiting and it worked fine.
check if you have the following lines in src/ApvlvCmds.cc
#ifdef __linux__
#include <gdk/gdkx.h>


2015-11-16 12:55 GMT+01:00 Kris <notifications@github.com>:

**Comment by drselump14** [comment]
@claudiocabral I can't find that line in src/ApvlvCmds.cc .. which branch I should compile actually? I just compiled master branch .

**Comment by claudiocabral** [comment]
compile the master in https://github.com/naihe2010/apvlv he already accepted my PR; I think my master branch is outdated because I was pushing to an already deleted branch called osx-compatible

**Comment by drselump14** [comment]
@claudiocabral Great, it works ... thanks a lot m8
