### ISSUE TITLE
Scroll to page not working

### ISSUE THREAD

**Issue by X4fyr** [naihe2010/apvlv#30]
For me the [count]G function isn't working. It behaves like theres no count and goes to last page.
I tried archlinux repository version 0.1.5 and self compiled from git. I have the issue for a long time now (haven't used apvlv very often) , so I can't remember when it appeared. Only setting I've done is `set autoscrolldoc=no`, but also occurs without this.

Is there a command like `:goto [page]`, so that I can test I just the binding not working, and workaround by setting manually? *Edit:* Found it. Simply `:[page]` and it is working.

**Comment by naihe2010** [comment]
I am very sorry. I had seen this issue, but forgot. 
Thank @serejkus .

**Comment by serejkus** [comment]
Not at all :)
