### ISSUE TITLE
open file window (Key command O) on 'cancel' creates $HOME in $HOME

### ISSUE THREAD

**Issue by vdksoda** [naihe2010/apvlv#33]
Opening the open file window and closing it creates a $HOME directory in $HOME. Here is the created folder structure.

```
$HOME
 $HOME
  .config
    dconf
      user
```

I am able to recreate this behaviour everytime which is what makes me suspect apvlv. But could be wrong.

Using version 0.1.5-rel on arch linux. Thanks for the great tool!

**Comment by naihe2010** [comment]
Please check your gnome, gtk or some other settings. apvlv should not create these directories.
