### ISSUE TITLE
error: ‘PACKAGE_NAME’ was not declared in this scope

### ISSUE THREAD

**Issue by amorellp** [naihe2010/apvlv#40]
Hi! I can't build apvlv in Ubuntu 15.10:

amp@albuntu:~/sources/apvlv$ make
[  7%] Building CXX object CMakeFiles/apvlv.dir/ApvlvMenu.o
/home/amp/sources/apvlv/src/ApvlvMenu.cc: In function ‘void apvlv::apvlv_menu_on_help_about()’:
/home/amp/sources/apvlv/src/ApvlvMenu.cc:134:64: error: ‘PACKAGE_NAME’ was not declared in this scope
     gtk_about_dialog_set_program_name (GTK_ABOUT_DIALOG (dia), PACKAGE_NAME);
                                                                ^
/home/amp/sources/apvlv/src/ApvlvMenu.cc:135:59: error: ‘PACKAGE_VERSION’ was not declared in this scope
     gtk_about_dialog_set_version (GTK_ABOUT_DIALOG (dia), PACKAGE_VERSION);
                                                           ^
CMakeFiles/apvlv.dir/build.make:215: recipe for target 'CMakeFiles/apvlv.dir/ApvlvMenu.o' failed
make[2]: *** [CMakeFiles/apvlv.dir/ApvlvMenu.o] Error 1
CMakeFiles/Makefile2:60: recipe for target 'CMakeFiles/apvlv.dir/all' failed
make[1]: *** [CMakeFiles/apvlv.dir/all] Error 2
Makefile:116: recipe for target 'all' failed
make: *** [all] Error 2
amp@albuntu:~/sources/apvlv$

any hint?

**Comment by naihe2010** [comment]
run cmake first.

**Comment by amorellp** [comment]
i did it. i executed "ccmake ." (i also tried with "ccmake src/"), i kept all the defaults, then i pressed "c" to configure and "g" to generate. am i missing smt?

**Comment by naihe2010** [comment]
`cmake . && make` ?

**Comment by amorellp** [comment]
This time it worked well (for Ubuntu 16 though) Thanks a lot!
