### ISSUE TITLE
Print

### ISSUE THREAD

**Issue by beli3ver** [naihe2010/apvlv#50]
Hello

is there a way to print a pdf with apvlv?
I mean to send the seen pdf to the printer?

Thanks

**Comment by naihe2010** [comment]
On Wed, 02 Aug 2017 09:57:03 +0000 (UTC)
Malte Kiefer <notifications@github.com> wrote:

> Hello
> 
> is there a way to print a pdf with apvlv?
> I mean to send the seen pdf to the printer?
> 
> Thanks
> 

command ':print' or ':pr'

**Comment by beli3ver** [comment]
Thanks
