### ISSUE TITLE
feature: 3-pages-continuous-scrolling (pull request draft)

### ISSUE THREAD

**Issue by alexander-n8hgeg5e** [naihe2010/apvlv#58]
The following changes since commit 6b23aeb233d468aa1d6df6a2facdc76b04f80bd3:

  update C++ standard to 11 and using nullptr, auto. (2019-12-10 16:05:45 +0800)

are available in the Git repository at:

  https://github.com/alexander-n8hgeg5e/apvlv.git for-origin

for you to fetch changes up to b90b93872d915539bd1ab2fda2b42ccc2cac25fc:

  fet: 3 pages continous scrolling (2020-03-12 04:57:31 +0100)

----------------------------------------------------------------
alexander-n8hgeg5e (1):
      fet: 3 pages continous scrolling

 src/ApvlvCore.cc | 54 +++++++++++++++++++++++++++++++++++++++++-------------
 src/ApvlvDoc.cc  | 35 ++++++++++++++++++++++++-----------
 src/ApvlvDoc.h   |  6 +++---
 3 files changed, 68 insertions(+), 27 deletions(-)

**Comment by naihe2010** [comment]
Thank you.

**Comment by alexander-n8hgeg5e** [comment]
Cool you merged it.
Maybe it ignores somewhat the options of the config file.
And I think I ignored the coding style.
Happy to see it merged.
