### ISSUE TITLE
Option to set fixed width and height of EPUB files in fullscreen mode

### ISSUE THREAD

**Issue by maxigaz** [naihe2010/apvlv#63]
I often read longer documents and books in fullscreen to minimise distraction. However, in apvlv, this always renders the text of EPUB documents at full width, making it inconvenient to read.

The desktop version of FBReader allows one to set margins so that the text is always centred. This is a great step in the right direction as in full screen the width of the text may be optimal. However, with the same margin settings, when the window of the reader is half the size of the screen and placed next to another window, the text becomes too narrow.

So, I would like to see the ability to set fixed width and height, which are forced regardless of the window size. If the window is bigger than the given dimension, the rest should be filled with a dark colour (or maybe even with a custom one), as if a PDF file was opened.

**Comment by naihe2010** [comment]
added.
