### ISSUE TITLE
Source ID xxxx was not found when attemting to remove it

### ISSUE THREAD

**Issue by aru-hackZ** [naihe2010/apvlv#64]
I just did install this awesome vim based pdf reader (among other formats), so I tried it calling the app from the command-line and I realized that, when i open a pdf (using `o`), it opens a new window where i pick a chapter of the book and then creates a new window where it opens the pdf (in the page where that chapter starts as expected). But there is an issu, the other windows aren't killed (or removed) like you see here:
![2020-08-19_19-07](https://user-images.githubusercontent.com/68018085/90667801-584daa00-e24f-11ea-8537-b9576f62a9d0.png)

And in the terminal where started the app i can see this errors:
![2020-08-19_19-08](https://user-images.githubusercontent.com/68018085/90667911-84692b00-e24f-11ea-9119-acd5393b245d.png)

Edit:
I don't know if not killing the window where you choose the chapter to view is default, but when I try to go to another chapter that window gives no answer, but the window where I'm reading the pdf.
p.e. in the chapter window i press the downwards arrow key, in the chapter window nothing happens, but where im reading the pdf it goes down.

Edit2:
Woah, just realized i had to `:q` in the pdf window to be able to access to the chapter window.
Maybe I should close this issue.

Pls ask for more info if you need it, and thanks!

**Comment by naihe2010** [comment]
fixed in version "ad9f937cbefb27785ea3676543a75e113ad066b5".
