### ISSUE TITLE
src/ApvlvInfo.h:28: bad header guard

### ISSUE THREAD

**Issue by dcb314** [naihe2010/apvlv#65]
apvlv-0.2.0/src/ApvlvInfo.h:28:9: warning: '_APVLV_INFO_H_' is used as a header guard here, followed by #define of a different macro [-Wheader-guard]
#ifndef _APVLV_INFO_H_
        ^~~~~~~~~~~~~~
/home/dcb32B/rpmbuild/BUILD/apvlv-0.2.0/src/ApvlvInfo.h:29:9: note: '_APVLV_INOF_H_' is defined here; did you mean '_APVLV_INFO_H_'?
#define _APVLV_INOF_H_

**Comment by naihe2010** [comment]
Thank you.
