### ISSUE TITLE
Feature request: improve documentation

### ISSUE THREAD

**Issue by igavronski** [naihe2010/apvlv#69]
Dear developers,
Thank you very much for this beautiful piece of software.
However, the version on Ubuntu repositories is quite old (0.1.5) and with bugs (probably dependencies). 
I would like to build it for my system.
Could you please add a couple of lines in the README.md with instructions for building it? I am not a developer, but I can type a couple of commands and build it myself, with the appropriate directions.
I tried to find those instructions in other places using search engines, to no avail.
Kind regards.

**Comment by naihe2010** [comment]
1. using cmake to generate Makefile. in top source dir, press: cmake .
2. execute make. press: make
3. (optional) make a package. press: make package. And, install it. 
4. or just press: sudo make install

**Comment by igavronski** [comment]
Dear @naihe2010, 

I am sorry, but this is not a change in the documentation. What I was suggesting was adding a subheading in the Readme.MD file with build instructions and package prerequisites.

Kind regards,
