### ISSUE TITLE
Question about the project's hosting 

### ISSUE THREAD

**Issue by gautaz** [naihe2010/apvlv#82]
Hello,

The [github's README](https://github.com/naihe2010/apvlv/blob/master/README.md) states:

> Apvlv is a open source software, was created by Alf and **was** hosted on [github](https://github.com/naihe2010/apvlv).

This seems to imply that the project is not hosted anymore on Github.

Is this on purpose?
In this case, where is now the project hosted?

If the project is still hosted on Github, perhaps the following statement would be more accurate:

> Apvlv is a open source software, was created by Alf and **is** hosted on [github](https://github.com/naihe2010/apvlv).

Does this reflect the initial intent?

G.

**Comment by naihe2010** [comment]
Thank you.

**Comment by gautaz** [comment]
You're welcome :slightly_smiling_face:.
Thank you for answering and maintaining this repo.
I can close this issue as the intent is now clear.
