### ISSUE TITLE
please upgrade apvlv to use webkit2gtk-4.1 OR webkitgtk-6.0 (GTK 4 and libsoup 3)

### ISSUE THREAD

**Issue by rosset** [naihe2010/apvlv#83]
Hi, please upgrade apvlv to use webkit2gtk-4.1 OR webkitgtk-6.0 (GTK 4 and libsoup 3)

apvlv-0.4.0]$ grep "webkit2gtk-4" * -irn
src/CMakeLists.txt:21:PKG_CHECK_MODULES(WEBKIT webkit2gtk-4.0 REQUIRED)

Thanks!

**Comment by pacho2** [comment]
I think this was fixed with:
https://github.com/naihe2010/apvlv/commit/39f783103e99b954991183cea2b5ccbd9add2a1a

**Comment by naihe2010** [comment]
> I think this was fixed with: [39f7831](https://github.com/naihe2010/apvlv/commit/39f783103e99b954991183cea2b5ccbd9add2a1a)

yes.
