### ISSUE TITLE
$HOME/.apvlvrc is not being read

### ISSUE THREAD

**Issue by FEER0** [naihe2010/apvlv#87]
when i execute `apvlv` it does not use my `.apvlvrc`.  
It works when I specify `apvlv -c $HOME/.apvlvrc`
### file:
```
-rw-r--r--. 1 redacted redacted    34 Nov 30 21:25 .apvlvrc
```
### `.apvlvrc`:
```
set content=no
set zoom=fitwidth

```
### version:
```
apvlv 0.5.0-rel
Please send bug report to Alf <naihe2010@126.com>

```
I have a workaround by setting an alias. Thank you for developing apvlv

**Comment by naihe2010** [comment]
It is fixed in this commit: https://github.com/naihe2010/apvlv/commit/4a56ac39e773717d25609a88da3e8ee75baa3659
